TOPDIR := $(realpath ../..)

CLEAN-FILES := data/*.c

PNG2C.ground  := --bitmap ground,640x16x1
PNG2C.ground2 := --bitmap ground2,640x16x1

PNG2C.tree-slim := --sprite slim,256,2
PNG2C.tree-bold := --sprite bold,256,2
PNG2C.just-tree := --sprite just,256,2

PNG2C.ghost := --sprite ghost,50,2

include $(TOPDIR)/build/effect.mk
