TOPDIR := $(realpath ../..)

CLEAN-FILES := data/tree-left.c data/ground.c

PNG2C.ground := --bitmap ground,640x16x1
PNG2C.tree-left := --sprite left,256,2
PNG2C.tree-slim := --sprite slim,256,2

include $(TOPDIR)/build/effect.mk
