TOPDIR := $(realpath ../..)

CLEAN-FILES := data/stencil3d-pal-?.c data/codi_02.c data/slayer-pat-??.c

LIBS := lib3d

PNG2C.stencil3d-pal-1 := --palette flatshade,16
PNG2C.stencil3d-pal-2 := --palette flatshade,16
PNG2C.stencil3d-pal-3 := --palette flatshade,16
PNG2C.stencil3d-pal-4 := --palette flatshade,16
PNG2C.stencil3d-pal-5 := --palette flatshade,16
PNG2C.slayer-pat-05 := --bitmap pattern_1,256x256x1
PNG2C.slayer-pat-06 := --bitmap pattern_2,256x256x1
OBJ2C.codi_02 := --scale 488.0 --mesh-name codi

include $(TOPDIR)/build/effect.mk
