TOPDIR := $(realpath ../..)

CLEAN-FILES := data/beam.c data/coq.c data/ring.c data/ufo.c data/bkg.c

PNG2C.bkg  := --bitmap bkg,320x256x1
PNG2C.ufo  := --bitmap ufo,104x39x4
PNG2C.ring := --bitmap ring,56x16x3

PNG2C.coq  := --sprite coq,24,1
PNG2C.beam := --sprite beam,200,2

include $(TOPDIR)/build/effect.mk
