TOPDIR := $(realpath ../..)

CLEAN-FILES := data/beam.c data/coq.c data/ring.c data/ufo.c

PNG2C.ufo  := --bitmap ufo,180x64x2
PNG2C.ring := --bitmap ring,128x32x2

PNG2C.coq  := --sprite coq,32,2
PNG2C.beam := --sprite beam,200,2

include $(TOPDIR)/build/effect.mk
