TOPDIR := $(realpath ../..)

CLEAN-FILES := data/loader.c data/ufo.c

PNG2C.loader := --bitmap loader,320x256x3 --palette loader,2
PNG2C.ufo    := --bitmap ufo,44x15x3

include $(TOPDIR)/build/effect.mk
