name: Demoscene

on:
  push

jobs:
  style:
    name: Python Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
      - name: Check Python code style
        run: bash style-python

  build:
    name: Build
    runs-on: ubuntu-latest
    container: cahirwpz/demoscene:latest
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1.2.3
      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'
          cache-dependency-path: tools/**/go.sum
      - name: Build everything
        run: |
          . /root/demoscene/bin/activate
          make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: effects
          path: effects/*/*.adf
